require 'yaml'

class Wihajster::Configuration
  attr_writer :config_name, :config_path

  class ConfigHash < BasicObject
    attr_accessor :__config

    def self.[](source)
      new(Hash[source])
    end

    def initialize(hash={})
      @hash = hash
    end

    def [](key)
      @hash[key]
    end

    def []=(key, value)
      prev = @hash[key]
      curr = @hash[key] = __convert(value)

      __config.save if prev != curr

      curr
    end

    def ==(other)
      other.is_a?(ConfigHash) && other.__hash == __hash
    end

    def __hash
      @hash
    end

    def __convert(object)
      converted = case object
      when ConfigHash
        object
      when Hash
        hash = {}
        object.each{|k,v| hash[k] = __convert(v)}
        ConfigHash[hash]
      when Array
        object.map {|e| convert(e) }
      else
        object
      end

      converted.__config = __config if converted.is_a?(ConfigHash)

      converted
    end

    def method_missing(name, *args, &block)
      return(super) if block

      sname, symname = name.to_s, name.to_sym
      case args.length
      when 0
        self[symname]
      when 1
       if sname[-1..-1] == "="
         self[sname[0..-2].to_sym] = args.first
       else
         super
       end
      else
        super
      end
    end
  end

  def initialize(profile)
    self.profile = profile
  end

  def config_name
    @config_name || @profile.empty? ? "wihajster.yml" : (@profile + ".yml")
  end

  def defaults
    default = {
      default: {
        joystick: { id: nil },
        printer:  { device: nil, speed: 115200, },
        scripts:  { monitor: true, },
      },
      "test_run" => {
        joystick: { id: 0 },
        printer:  { device: nil, speed: 115200, },
        scripts:  { monitor: false, },
      },
      "events_test" => {
        joystick: { id: 0 },
        printer:  { device: nil, speed: 115200, },
        scripts:  { monitor: false, },
      },
    }

    default[@profile] || default[:default]
  end

  def config_path
    @config_path || File.join(Wihajster.working_dir, config_name)
  end

  def data
    @data
  end

  def to_yaml
    YAML.dump(@data)
  end

  def convert(hash)
    config_hash = ConfigHash[hash]
    config_hash.__config = self

    config_hash
  end

  def load
    if File.exist?(config_path)
      @raw_config = YAML.load_file(config_path)
      @data = convert( @raw_config )
    else
      @data = convert( defaults )
    end

    self
  end

  def save
    File.open(config_path, "w") do |f|
      f.puts "# YAML config generated by wihajster on #{Time.now.strftime("%Y-%m-%d %H:%M")}."
      f.puts "# Changes made by external tools during runtime of wihajster"
      f.puts "# will be ignored, and might be overriden."
      f.write(to_yaml)
    end

    self
  end

  def profile=(profile)
    @profile = profile
    load
  end
end
