require 'yaml'

class Wihajster::Configuration
  attr_writer :config_name, :config_path, :config

  class OpenStructHash < Hash
    def method_missing(name, *args, &block)
      return(super) if block

      case args.length
      when 0
        self[name]
      when 1
       if name[-1..-1] == "="
         self[name[0..-2]] = args.first
       else
         super
       end
      else
        super
      end
    end
  end

  def default
    {
      joystick: {id: nil},
      printer: {
        device: nil,
        speed: 115200,
      },
      scripts: {
        monitor: true,
      },
    }
  end

  def initialize(profile)
    @profile = profile
    @auto_save = true
    self.load
  end

  def config_name
    @config_name || @profile.empty? ? "wihajster.yml" : (@profile + ".yml")
  end

  def config_path
    @config_path || File.join(Wihajster.working_dir, @config_name)
  end

  def config
    @config ||= convert(default)
  end

  def to_yaml
    YAML.dump(@config)
  end

  def [](key)
    config[key]
  end

  def []=(key, value)
    config[key]=value
    save if @auto_save

    value
  end

  def convert(object)
    case object
    when OpenStructHash
      object
    when Hash
      hash = {}
      object.each{|k,v| hash[k] = recursive_ostruct(v)}
      OpenStructHash.new(hash)
    when Array
      object.map {|e| recursive_ostruct(e) }
    else
      object
    end
  end

  def load
    if File.exist?(config_path)
      @raw_config = YAML.load_file(config_path)
      @config = convert( @raw_config )
    end

    self
  end

  def save
    File.open(config_path, "w") do |f|
      f.puts "# YAML config generated by wihajster on #{Time.now.strftime("%Y-%m-%d %H:%M")}."
      f.puts "# Changes made by external tools during runtime of wihajster"
      f.puts "# will be ignored, and might be overriden."
      f.write(to_yaml)
    end

    self
  end

  def temporary!
    @auto_save = false
  end
end
